# Generated by Django 3.0.2 on 2020-01-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='actual_deal_status',
            new_name='deal_is_online',
        ),
    ]
