# Generated by Django 3.0.2 on 2020-01-25 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0002_auto_20200125_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='like_counter',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='user_like',
            field=models.ManyToManyField(related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
