# Generated by Django 3.0.2 on 2020-01-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20200114_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='link_to_shop',
            field=models.URLField(blank=True, null=True),
        ),
    ]
