# Generated by Django 3.0.2 on 2020-01-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_shop_link_to_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='brands',
            new_name='brand',
        ),
    ]
