# Generated by Django 3.0.2 on 2020-01-26 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0004_auto_20200125_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='user_like',
            field=models.ManyToManyField(null=True, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
