# Generated by Django 3.0.2 on 2020-02-02 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0006_auto_20200126_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
