# Generated by Django 3.0.2 on 2020-02-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_auto_20200202_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
    ]
