# Generated by Django 3.0.2 on 2020-01-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_auto_20200116_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
