# Generated by Django 3.0.2 on 2020-02-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_shop_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
