# Generated by Django 3.0.2 on 2020-02-08 15:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_auto_20200207_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
