# Generated by Django 3.0.2 on 2020-02-08 15:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_auto_20200208_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
