# Generated by Django 3.0.2 on 2020-02-09 14:49

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_auto_20200209_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
